apiVersion: v1
kind: Service
metadata:
  name: cms
spec:
  selector:
    app: cms
  ports:
  - port: 3838
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  labels:
    app: cms
spec:
  selector:
    matchLabels:
      app: cms
  replicas: 2
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
      - name: cms
        image: bdwyer/vs-cms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3838
        resources:
          requests:
            memory: "2Gi"
      imagePullSecrets:
        - name: dockerhub
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cms
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - cms.k8s.sfo2.bdwy.cloud
      secretName: cms-tls
  rules:
  - host: cms.k8s.sfo2.bdwy.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cms
            port:
              number: 3838

